language: ko

reviews:
  high_level_summary: true
  review_status: true
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - dev

path_instructions: [ ]

rules:
  java:
    enabled: true
    version: 17
    prefer_lombok: true

  spring:
    enabled: true
    version: "3.5.3"

focus_areas:
  - 보안
  - 성능

custom_checks:
  - name: "한국어 주석 권장"
    pattern: "//.*[a-zA-Z]{20,}"
    message: "긴 영어 주석은 가능하면 한국어로 작성해 주세요."
    severity: "suggestion"

# 꼭 필요한 경우에만 리포트 관리
metrics:
  generate_reports: false

# 다이어그램
diagrams:
  sequence_diagrams:
    enabled: true
    auto_generate: false    # 자동생성 비활성화(기본)
    generate_on_complexity: 10   # 복잡도 10 이상 function/method에서만 생성
    focus_on_interactions: true

visualization:
  include_architecture_insights: false
