services:
  backend:
    container_name: lunchchat-backend
    # 프로덕션: GitHub Actions에서 빌드한 이미지 사용
    image: ${DOCKER_REGISTRY:-xoo1228}/${DOCKER_IMAGE_NAME:-lunchchat-backend}:${IMAGE_TAG:-latest}

    # 로컬 개발: Dockerfile로 빌드
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    environment:
      # 기본 Spring Boot 설정
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - SERVER_PORT=8080

      # 데이터베이스 설정
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PW=${DB_PW}

      # Redis 설정 (캐시 + pub/sub)
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}

      # JPA 설정
      - JPA_DDL_AUTO=${JPA_DDL_AUTO:-validate}
      - JPA_SHOW_SQL=${JPA_SHOW_SQL:-false}

      # Flyway 설정
      - FLYWAY_BASELINE_ON_MIGRATE=${FLYWAY_BASELINE_ON_MIGRATE:-true}
      - FLYWAY_CLEAN_DISABLED=${FLYWAY_CLEAN_DISABLED:-true}

      # 로깅 설정
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - SQL_LOG_LEVEL=${SQL_LOG_LEVEL:-WARN}

      # WebSocket & Chat 설정
      - WEBSOCKET_ALLOWED_ORIGINS=${WEBSOCKET_ALLOWED_ORIGINS:-*}
      - CHAT_REDIS_CHANNEL=${CHAT_REDIS_CHANNEL:-lunchchat}


      # JWT/OAuth 설정
      - SECRET_KEY=${SECRET_KEY}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}

      # FCM 설정
      - FCM_SERVICE_ACCOUNT_JSON=${FCM_SERVICE_ACCOUNT_JSON:-}
      - FCM_SERVICE_ACCOUNT_FILE=${FCM_SERVICE_ACCOUNT_FILE:-}

    restart: unless-stopped

    volumes:
      - ./logs:/var/log/lunchchat
      - ./firebase-service-account-key.json:/app/firebase-service-account-key.json:ro

    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # 로컬 개발용 서비스들 (프로덕션에서는 AWS 관리형 서비스 사용)
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=lunchchatdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    profiles: [ "local" ]

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    profiles: [ "local" ]

volumes:
  mysql_data:
  redis_data: