spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
    hikari:
      maximum-pool-size: 5

  jwt:
    header: authorization
    secret: ${SECRET_KEY}
    access-token-validity-in-seconds: 3600
    refresh-token-validity-in-seconds: 604800

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: "https://lunchchat.kro.kr/auth/callback/google"
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul

  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss

  flyway:
    enabled: false
    baseline-on-migrate: true
    clean-disabled: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

fcm:
  service-account-json: ${FCM_SERVICE_ACCOUNT_JSON:}

server:
  port: ${SERVER_PORT}

logging:
  level:
    com.lunchchat: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.flywaydb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"