spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul

  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss

  jwt:
    header: authorization
    secret: ${SECRET_KEY}
    access-token-validity-in-seconds: 3600
    refresh-token-validity-in-seconds: 604800

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: "https://lunchchat.kro.kr/auth/callback/google"
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: true
    validate-on-migrate: true

  data:
    redis:
      timeout: 30000ms
    
    mongodb:
      uri: ${MONGO_URI}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.0
          max-completion-tokens: 32

google:
  sheet:
    id: ${GOOGLE_SHEET_ID}

fcm:
  service-account-file: ${FCM_SERVICE_ACCOUNT_FILE:}

server:
  port: 8080

logging:
  level:
    com.lunchchat: INFO
    org.springframework.security: WARN
    org.flywaydb: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"
