- name: Deploy Monitoring Stack
  hosts: monitoring
  become: yes
  gather_facts: no
  vars:
    monitoring_dir: "/home/ubuntu/lunchchat-monitoring"

  tasks:
    - name: Debug paths for troubleshooting
      debug:
        msg:
          - "Playbook directory: {{ playbook_dir }}"
          - "Looking for monitoring files in: {{ playbook_dir }}/../monitoring/"

    - name: Ensure base monitoring directory exists
      file:
        path: "{{ monitoring_dir }}"
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Copy monitoring stack files from Git repo
      copy:
        src: "{{ playbook_dir }}/../monitoring/"
        dest: "{{ monitoring_dir }}/"
        mode: '0644'
        owner: ubuntu
        group: ubuntu

    - name: Ensure prometheus config directory exists
      file:
        path: "{{ monitoring_dir }}/monitoring/prometheus"
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Ensure alertmanager config directory exists
      file:
        path: "{{ monitoring_dir }}/monitoring/alertmanager"
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Template out prometheus.yml
      template:
        src: "{{ playbook_dir }}/../monitoring/prometheus/prometheus.yml.template"
        dest: "{{ monitoring_dir }}/monitoring/prometheus/prometheus.yml"
        mode: '0644'
        owner: ubuntu
        group: ubuntu
      vars:
        MONITORING_ENVIRONMENT: "{{ monitoring_environment | default('production') }}"

    - name: Template out alertmanager.yml
      template:
        src: "{{ playbook_dir }}/../monitoring/alertmanager/alertmanager.yml.template"
        dest: "{{ monitoring_dir }}/monitoring/alertmanager/alertmanager.yml"
        mode: '0644'
        owner: ubuntu
        group: ubuntu
      vars:
        DISCORD_WEBHOOK_URL: "{{ discord_webhook_url }}"

    - name: Start monitoring stack with environment variables from AWX
      community.docker.docker_compose_v2:
        project_src: "{{ monitoring_dir }}/monitoring"
        state: present
        environment:
          PROJECT_NAME: lunchchat
          MONITORING_ENVIRONMENT: "{{ monitoring_environment | default('production') }}"
          PROMETHEUS_PORT: "{{ prometheus_port }}"
          GRAFANA_PORT: "{{ grafana_port }}"
          NODE_EXPORTER_PORT: "{{ node_exporter_port }}"
          REDIS_EXPORTER_PORT: "{{ redis_exporter_port }}"
          PUSHGATEWAY_PORT: "{{ pushgateway_port }}"
          ALERTMANAGER_PORT: "{{ alertmanager_port }}"
          GRAFANA_ADMIN_USER: "admin"
          GRAFANA_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
          DISCORD_WEBHOOK_URL: "{{ discord_webhook_url }}"
          REDIS_ADDR: "{{ redis_addr }}"