- name: Deploy Monitoring Stack
  hosts: monitoring # GCP 인벤토리에서 생성될 'monitoring' 그룹을 대상으로 실행
  become: yes
  gather_facts: no
  vars:
    monitoring_dir: "/home/ubuntu/lunchchat-monitoring"

  tasks:
    - name: Copy monitoring stack files from Git repo
      copy:
        src: ./monitoring/
        dest: "{{ monitoring_dir }}/"

    - name: Template out prometheus.yml
      template:
        src: monitoring/prometheus/prometheus.yml.template
        dest: "{{ monitoring_dir }}/monitoring/prometheus/prometheus.yml"
      vars:
        MONITORING_ENVIRONMENT: "{{ monitoring_environment | default('production') }}"

    - name: Template out alertmanager.yml
      template:
        src: monitoring/alertmanager/alertmanager.yml.template
        dest: "{{ monitoring_dir }}/monitoring/alertmanager/alertmanager.yml"
      vars:
        DISCORD_WEBHOOK_URL: "{{ discord_webhook_url }}"

    - name: Start monitoring stack with environment variables from AWX
      community.docker.docker_compose_v2:
        project_src: "{{ monitoring_dir }}/monitoring"
        state: present
        environment:
          PROJECT_NAME: lunchchat
          MONITORING_ENVIRONMENT: "{{ monitoring_environment | default('production') }}"
          PROMETHEUS_PORT: "{{ prometheus_port }}"
          GRAFANA_PORT: "{{ grafana_port }}"
          NODE_EXPORTER_PORT: "{{ node_exporter_port }}"
          REDIS_EXPORTER_PORT: "{{ redis_exporter_port }}"
          PUSHGATEWAY_PORT: "{{ pushgateway_port }}"
          ALERTMANAGER_PORT: "{{ alertmanager_port }}"
          GRAFANA_ADMIN_USER: "admin"
          GRAFANA_ADMIN_PASSWORD: "{{ grafana_admin_password }}"
          DISCORD_WEBHOOK_URL: "{{ discord_webhook_url }}"
          REDIS_ADDR: "{{ redis_addr }}"